sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cbolik/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cbolik/udemy-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "udemy-docker-react2"
  env: "Udemydockerreact2-env"
  bucket_name: "elasticbeanstalk-eu-central-1-698634647164"
  bucket_path: "udemy-docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
