sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cbolik/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cbolik/udemy-docker-react npm run test -- --coverage
